name: 'backstage-techdocs'
description: 'action to build and deploy techdocs'
inputs:
  gcs_bucket_name:
    description: 'The name of the Google Cloud Storage bucket to publish the TechDocs site to'
    required: true
  entity_namespace:
    description: 'The namespace of the entity to publish the TechDocs site to'
    required: true
    default: 'default'
  entity_kind:
    description: 'The kind of the entity to publish the TechDocs site to'
    required: true
  entity_name:
    description: 'The name of the entity to publish the TechDocs site to'
    required: true
  workload_identity_provider:
    description: 'The Workload Identity Provider to use for authentication'
    required: true
  service_account:
    description: 'The service account to use for authentication'
    required: true
  project_id:
    description: 'The Google Cloud project ID to use for authentication'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - id: 'auth'
      uses: google-github-actions/auth@v0.5.0
      with:
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}
        project_id: ${{ inputs.project_id }}

    - uses: actions/setup-node@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install techdocs-cli
      shell: bash
      run: sudo npm install -g @techdocs/cli

    - name: Install mkdocs and mkdocs plugins
      shell: bash
      run: python -m pip install mkdocs-techdocs-core==1.*

    - name: Generate docs site
      shell: bash
      run: techdocs-cli generate --no-docker --verbose

    - name: Publish docs site
      shell: bash
      run: techdocs-cli publish --publisher-type googleGcs --storage-name ${{ inputs.gcs_bucket_name }} --entity ${{ inputs.entity_namespace }}/${{ inputs.entity_kind }}/${{ inputs.entity_name }}