# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "backstage-techdocs-action"
  tags:
  - "public"
spec:
  type: "library"
  lifecycle: "production"
  owner: "skip"
  system: "utviklerportal"
